version: "3.2"

services:

  rabbitmq-server:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq-server"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    command: ["php", "-S", "0.0.0.0:8000", "-t", "/var/www/html"]
    ports:
      - "8000"
    volumes:
      - ./docker/config/php.ini:/usr/local/etc/php/php.ini
      - ./:/var/www/html/:z
    tty: true
    depends_on:
     - rabbitmq-server
    links:
      - rabbitmq-server

volumes:
  rabbitmq-data: